name: On-demand self-hosted AWS EC2 and Azure runner for GitHub Actions
description: GitHub Action for automatic creation and registration AWS EC2 instance and Azure as a GitHub Actions self-hosted runner.
author: Elana Zobin
branding:
  icon: 'box'
  color: 'purple'
inputs:
  clouds:
    description: >-
      Specify which cloud runner you want to run:
        - ec2 - runs ec2 only
        - azure - runs azure only 
        - both - runs both runners
    required: false
    default: 'both'
  mode:
    description: >-
      Specify here which mode you want to use:
        - 'start' - to start a new runner;
        - 'stop' - to stop the previously created runner.
    required: true
  status: 
    description: >-
      status of the workflow. Required for stop mode
    required: false
  github-token:
    description: >-
      GitHub Personal Access Token with the 'repo' scope assigned.
    required: true
  runner-user:
    description: >-
      user to be used as runner of the virtual machine.
    required: true
  subnet: 
    description: >-
        subnet info in the format N.N.N.N. Required for start mode
    required: false
    default: 10.0.0.0
  public-keys-dir: 
    description: >-
        full path to the directory with public keys to supply to VM
    required: false
  ec2-access-key-id:
    description: >-
      aws key Id
    required: true
  ec2-secret-access-key:
    description: >-
      aws secret access key
    required: true
  ec2-region: 
    description: >-
      aws registration
    required: true
  ec2-image:
    description: >-
      EC2 Image (AMI) name. The new runner will be launched from this image.
      This input is required if you use the 'start' mode.
    required: false
  ec2-instance-type:
    description: >-
      EC2 Instance Type. 
      This input is required if you use the 'start' mode.
    required: false
  ec2-vpc-name:
    description: >-
      VPC Id to run instance in. Required for start mode
    required: false
  ec2-iam-role-name:
    description: >-
      IAM Role Name to attach to the created EC2 instance.
      This requires additional permissions on the AWS role used to launch instances.
    required: false
  ec2-tags:
    description: >-
      Specifies tags to add to the EC2 instance and any attached storage. 
      This field is a stringified JSON array of tag objects, each containing a `Key` and `Value` field
    required: false
  az-subscription-id: 
    description: >-
        Azure secuprity information
    required: true
  az-client-id: 
    description: >-
        Azure secuprity information
    required: true
  az-tenant-id: 
    description: >-
        Azure secuprity information
    required: true
  az-secret: 
    description: >-
        Azure secuprity information
    required: false
  az-image: 
    description: >-
        Image locationand name in the format groupName:imageName
    required: false
  az-location: 
    description: >-
        geolocation , like westus
    required: false
  az-vm-size: 
    description: >-
        one of teh available vm sizes from Asure
    required: false

outputs:
  run-ons:
    description: >-
      JSON string that contains array of available self-hosted runners 
        {
          ec2: <github runner label>
          azure: <github runner label>
        }
runs:
  using: node16
  main: ./dist/index.js
